name: Build, Run and Test Docker on GitHub Actions

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create config.json from TRAVEL_PLANNER_SECRET
        if: ${{ secrets.TRAVEL_PLANNER_SECRET != '' }}
        run: |
          printf '%s' "${{ secrets.TRAVEL_PLANNER_SECRET }}" > config.json
          python3 -m json.tool config.json >/dev/null
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build image
        run: |
          docker build -t travel_planner:test .

      - name: Run container
        run: |
          # run in detached mode and map port 8080 to container 80
          docker run -d --name travel_planner_test -p 8080:80 travel_planner:test
          # wait for service to come up
          timeout=30
          echo "Waiting for service to be ready..."
          for i in $(seq 1 $timeout); do
            if curl -sS http://localhost:8080/ >/dev/null; then
              echo "Service is up"
              break
            fi
            sleep 1
          done

      - name: Smoke test
        run: |
          curl -f http://localhost:8080/ || (docker logs travel_planner_test && exit 1)

      - name: Stop container
        if: always()
        run: |
          docker stop travel_planner_test || true
          docker rm travel_planner_test || true

      - name: Publish to GHCR (optional)
        if: github.event_name != 'pull_request' && secrets.GITHUB_TOKEN != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
